#!/usr/bin/env python3
"""DLP File Transfer Simulator — one-click launcher.

This is the single entry point for the bundled executable.
On first run it walks the user through setup, deploys test files,
and starts the file-watcher automation.

Usage (development):
    python launcher.py

Usage (bundled exe):
    DLPSimulator.exe
"""

from __future__ import annotations

import logging
import os
import platform
import random
import shutil
import sys
import time
from pathlib import Path

import yaml
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Resolve paths — works both in dev and inside a PyInstaller bundle.
# PyInstaller sets sys._MEIPASS to the temp extraction folder.
# ---------------------------------------------------------------------------

def _base_dir() -> Path:
    """Return the base directory where bundled data files live."""
    if getattr(sys, "frozen", False):
        # Running as a PyInstaller bundle
        return Path(sys._MEIPASS)  # type: ignore[attr-defined]
    # Running as plain Python
    return Path(__file__).resolve().parent


BASE_DIR = _base_dir()
TEST_FILES_DIR = BASE_DIR / "detectors_profile_test_files"
DEFAULT_CONFIG = BASE_DIR / "config.yaml"
ENV_EXAMPLE = BASE_DIR / ".env.example"

VERSION = "1.0.0"


# ---------------------------------------------------------------------------
# Working directory — where .env, inbox, and runtime state live.
# ---------------------------------------------------------------------------

def _work_dir() -> Path:
    home = Path.home()
    return home / "DLPSimulator"


WORK_DIR = _work_dir()


# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------

def _banner() -> None:
    print()
    print("  ╔══════════════════════════════════════════╗")
    print(f"  ║   DLP File Transfer Simulator v{VERSION}    ║")
    print("  ║   Palo Alto Networks — Lab Use Only      ║")
    print("  ╚══════════════════════════════════════════╝")
    print()


# ---------------------------------------------------------------------------
# First-run setup wizard
# ---------------------------------------------------------------------------

def _setup_wizard(env_path: Path) -> None:
    """Interactive CLI wizard that generates a .env file."""
    print("  [First-Run Setup]\n")

    os_name = platform.system()
    print(f"  Detected OS: {os_name}")
    print()

    # -- Target app --
    print("  Which app should receive uploaded files?")
    print("    1. Slack (native desktop app — no API key needed)")
    print("    2. Teams (browser — needs Anthropic API key)")
    print("    3. Telegram (browser — needs Anthropic API key)")
    print("    4. Gmail (browser — needs Anthropic API key)")
    print("    5. Multiple / Custom (advanced)")
    choice = input("  Choose [1]: ").strip() or "1"

    app = {
        "1": "slack", "2": "teams", "3": "telegram",
        "4": "gmail", "5": "slack",
    }.get(choice, "slack")

    # -- App-specific config --
    channel = "#general"
    team = ""
    contact = ""
    recipient = ""
    anthropic_key = ""

    if app == "slack":
        channel = input("  Slack channel [#general]: ").strip() or "#general"
    elif app == "teams":
        team = input("  Teams team name: ").strip()
        channel = input("  Teams channel [General]: ").strip() or "General"
    elif app == "telegram":
        contact = input("  Telegram chat/contact name: ").strip()
    elif app == "gmail":
        recipient = input("  Gmail recipient email: ").strip()

    # -- API key (needed for non-Slack apps) --
    if app != "slack":
        print()
        print("  Claude Computer Use requires an Anthropic API key for")
        print("  vision-based browser automation.")
        anthropic_key = input("  Anthropic API key (or press Enter to skip): ").strip()

    # -- Watch folder --
    inbox = WORK_DIR / "inbox"
    custom = input(f"  Watch folder [{inbox}]: ").strip()
    if custom:
        inbox = Path(custom)

    # -- Write .env --
    lines = [
        "# Auto-generated by DLP Simulator setup wizard",
        f"# {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "LOG_LEVEL=INFO",
        f"WATCH_FOLDER={inbox}",
        "",
        "# Desktop Agent",
        f"ANTHROPIC_API_KEY={anthropic_key}",
        "DESKTOP_AGENT_MODEL=claude-sonnet-4-20250514",
        "DESKTOP_AGENT_MAX_STEPS=30",
        f"DESKTOP_AGENT_SCREENSHOT_DIR={WORK_DIR / 'screenshots'}",
        "",
        "# Local copy destination",
        f"LOCAL_COPY_DEST={WORK_DIR / 'outbox'}",
        "",
        "# DLP popup detection",
        "DLP_CONFIDENCE=0.8",
        "DLP_WAIT_SECONDS=3",
    ]
    env_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n  ✓ Config saved to {env_path}")

    # -- Write config.yaml tailored to chosen app --
    _write_config(app, channel, team, contact, recipient)

    return inbox


def _write_config(
    app: str, channel: str, team: str, contact: str, recipient: str,
) -> None:
    """Generate a config.yaml targeting the chosen app."""
    config_path = WORK_DIR / "config.yaml"

    handler: dict = {"type": "desktop_agent", "app": app}
    if app == "slack":
        handler["channel"] = channel
    elif app == "teams":
        handler["team"] = team
        handler["channel"] = channel
    elif app == "telegram":
        handler["chat"] = contact
    elif app == "gmail":
        handler["recipient"] = recipient

    config = {
        "rules": [
            {
                "name": "dlp_test_all",
                "pattern": "*",
                "handlers": [
                    handler,
                    {"type": "local_copy"},
                ],
            },
        ],
    }
    config_path.write_text(yaml.dump(config, default_flow_style=False), encoding="utf-8")
    print(f"  ✓ Rules saved to {config_path}")


# ---------------------------------------------------------------------------
# Deploy test files
# ---------------------------------------------------------------------------

def _deploy_test_files(inbox: Path, count: int | None = None) -> int:
    """Copy test files from the bundle into the inbox folder."""
    inbox.mkdir(parents=True, exist_ok=True)

    if not TEST_FILES_DIR.is_dir():
        print(f"  ⚠ Test files not found at {TEST_FILES_DIR}")
        return 0

    files = [
        f for f in TEST_FILES_DIR.rglob("*")
        if f.is_file() and not f.name.startswith(".")
    ]
    if not files:
        print("  ⚠ No test files found.")
        return 0

    if count is not None:
        files = random.sample(files, min(count, len(files)))

    copied = 0
    for src in files:
        dest = inbox / src.name
        if dest.exists():
            dest = inbox / f"{src.stem}_{int(time.time())}{src.suffix}"
        shutil.copy2(src, dest)
        copied += 1

    print(f"  ✓ {copied} test file(s) deployed to {inbox}")
    return copied


# ---------------------------------------------------------------------------
# Start watcher
# ---------------------------------------------------------------------------

def _start_watcher(config_path: Path) -> None:
    """Load config and start the file watcher (blocking)."""
    # Make sure our modules are importable
    file_transfer_dir = BASE_DIR
    if str(file_transfer_dir) not in sys.path:
        sys.path.insert(0, str(file_transfer_dir))

    import watcher  # noqa: E402 — late import after sys.path fix

    with open(config_path, encoding="utf-8") as fh:
        config = yaml.safe_load(fh)

    raw_rules = config.get("rules", [])
    rules = watcher.build_rules(raw_rules)

    if not rules:
        print("  ✗ No valid rules — check your config.")
        return

    watch_folder = Path(os.getenv("WATCH_FOLDER", str(WORK_DIR / "inbox")))
    watch_folder.mkdir(parents=True, exist_ok=True)

    print(f"  ✓ Watcher started — monitoring {watch_folder}")
    print("    Drop files into the inbox to trigger DLP-visible transfers.")
    print("    Press Ctrl+C to stop.\n")

    watcher.start(watch_folder, rules)


# ---------------------------------------------------------------------------
# Interactive menu
# ---------------------------------------------------------------------------

def _menu(inbox: Path, config_path: Path, env_path: Path) -> None:
    """Post-setup interactive menu."""
    while True:
        print()
        print("  ┌─────────────────────────────────┐")
        print("  │  [S] Seed more test files        │")
        print("  │  [R] Run watcher now              │")
        print("  │  [C] Re-run setup wizard          │")
        print("  │  [Q] Quit                         │")
        print("  └─────────────────────────────────┘")
        choice = input("  > ").strip().lower()

        if choice == "s":
            try:
                n = int(input("  How many files? [3]: ").strip() or "3")
            except ValueError:
                n = 3
            _deploy_test_files(inbox, count=n)

        elif choice == "r":
            _start_watcher(config_path)

        elif choice == "c":
            inbox = _setup_wizard(env_path)
            load_dotenv(env_path, override=True)

        elif choice == "q":
            print("  Goodbye.")
            break

        else:
            print("  Invalid choice.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    _banner()

    WORK_DIR.mkdir(parents=True, exist_ok=True)

    env_path = WORK_DIR / ".env"
    config_path = WORK_DIR / "config.yaml"

    # First-run detection
    if not env_path.is_file():
        inbox = _setup_wizard(env_path)
        load_dotenv(env_path, override=True)
        _setup_logging()
        _deploy_test_files(Path(inbox))
        print()
        _menu(Path(inbox), config_path, env_path)
    else:
        # Returning user
        load_dotenv(env_path, override=True)
        _setup_logging()
        inbox = Path(os.getenv("WATCH_FOLDER", str(WORK_DIR / "inbox")))
        print(f"  Config loaded from {env_path}")
        print(f"  Watch folder: {inbox}")
        _menu(inbox, config_path, env_path)


def _setup_logging() -> None:
    level = getattr(logging, os.getenv("LOG_LEVEL", "INFO").upper(), logging.INFO)
    logging.basicConfig(
        level=level,
        format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


if __name__ == "__main__":
    main()
